#!/usr/bin/env python3
"""
MA Hunting Calendar Sync
Reads seasons.json (generated by scrape.py) and syncs events to three
Google Calendars: Hunting, Furbearer/Trapping, and Migratory Bird.
"""
import hashlib
import json
import logging
import os
import sys
from datetime import date, datetime, timedelta, timezone
from logging.handlers import RotatingFileHandler
from pathlib import Path

from notify import send_status_email

from google.auth import default as google_auth_default
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# -- Logging -------------------------------------------------------------------
_log_dir = Path(__file__).parent / "logs"
_log_dir.mkdir(exist_ok=True)

_fmt = logging.Formatter("%(asctime)s %(levelname)s %(message)s")
_root = logging.getLogger()
_root.setLevel(logging.INFO)

_sh = logging.StreamHandler(sys.stdout)
_sh.setFormatter(_fmt)
_root.addHandler(_sh)

_fh = RotatingFileHandler(_log_dir / "sync.log", maxBytes=1_000_000, backupCount=3)
_fh.setFormatter(_fmt)
_root.addHandler(_fh)

logger = logging.getLogger(__name__)

# -- Config --------------------------------------------------------------------
HUNTING_CALENDAR_ID   = os.environ.get("HUNTING_CALENDAR_ID",   "primary")
FURBEARER_CALENDAR_ID = os.environ.get("FURBEARER_CALENDAR_ID", "primary")
MIGRATORY_CALENDAR_ID = os.environ.get("MIGRATORY_CALENDAR_ID", "primary")
SCOPES = ["https://www.googleapis.com/auth/calendar"]

SEASONS_FILE = Path(__file__).parent / "seasons.json"

MA_HUNTING_URL = (
    "https://www.mass.gov/info-details/"
    "2026-hunting-and-freshwater-fishing-season-summary"
)

# -- Data loading --------------------------------------------------------------
def load_seasons() -> list[dict]:
    if not SEASONS_FILE.exists():
        logger.error("seasons.json not found — run scrape.py locally first")
        sys.exit(1)
    rows = json.loads(SEASONS_FILE.read_text(encoding="utf-8"))
    logger.info("Loaded %d rows from seasons.json", len(rows))
    return rows


# -- Event building ------------------------------------------------------------
def _event_id(season: str, zone: str, start: str) -> str:
    key = f"{season}|{zone}|{start}".lower()
    return "ma_" + hashlib.md5(key.encode()).hexdigest()[:16]


def build_event(row: dict, start_iso: str, end_iso: str) -> dict:
    zone = row["zone"]
    summary = f"MA: {row['season']}"
    if zone and zone.lower() not in ("statewide", ""):
        summary += f" ({zone})"

    description = "\n".join([
        f"Section: {row['section']}",
        f"Dates: {row['date_str']}",
        f"Zone: {zone}",
        "",
        f"Source: {MA_HUNTING_URL}",
    ])

    start_date = date.fromisoformat(start_iso)
    end_date   = date.fromisoformat(end_iso)
    # Google Calendar all-day end is exclusive
    end_exclusive = (end_date + timedelta(days=1)).isoformat()

    return {
        "summary":     summary,
        "description": description,
        "start":       {"date": start_iso},
        "end":         {"date": end_exclusive},
        "extendedProperties": {
            "private": {
                "ma_hunting_id":   _event_id(row["season"], zone, start_iso),
                "ma_hunting_sync": "true",
            }
        },
    }


# -- Calendar helpers ----------------------------------------------------------
def get_calendar_service():
    creds, _ = google_auth_default(scopes=SCOPES)
    return build("calendar", "v3", credentials=creds, cache_discovery=False)


def get_existing_events(service, calendar_id: str) -> dict[str, dict]:
    events: dict[str, dict] = {}
    page_token = None
    while True:
        result = (
            service.events()
            .list(
                calendarId=calendar_id,
                privateExtendedProperty="ma_hunting_sync=true",
                maxResults=250,
                pageToken=page_token,
                showDeleted=False,
            )
            .execute()
        )
        for ev in result.get("items", []):
            ma_id = ev.get("extendedProperties", {}).get("private", {}).get("ma_hunting_id")
            if ma_id:
                events[ma_id] = ev
        page_token = result.get("nextPageToken")
        if not page_token:
            break
    return events


def sync_calendar(service, calendar_id: str, rows: list[dict], label: str) -> dict:
    existing = get_existing_events(service, calendar_id)
    logger.info("[%s] %d existing  |  %d source rows", label, len(existing), len(rows))

    wanted: dict[str, dict] = {}
    for row in rows:
        for start_iso, end_iso in row["dates"]:
            ma_id = _event_id(row["season"], row["zone"], start_iso)
            wanted[ma_id] = build_event(row, start_iso, end_iso)

    created = updated = deleted = errors = 0

    for ma_id, event in wanted.items():
        try:
            if ma_id in existing:
                service.events().patch(
                    calendarId=calendar_id,
                    eventId=existing[ma_id]["id"],
                    body=event,
                ).execute()
                updated += 1
                logger.info("[%s] Updated: %s", label, event["summary"])
            else:
                service.events().insert(
                    calendarId=calendar_id,
                    body=event,
                ).execute()
                created += 1
                logger.info("[%s] Created: %s", label, event["summary"])
        except HttpError as e:
            logger.error("[%s] API error for %s: %s", label, event["summary"], e)
            errors += 1
        except Exception as e:
            logger.error("[%s] Unexpected error for %s: %s", label, event["summary"], e)
            errors += 1

    for ma_id, ev in existing.items():
        if ma_id not in wanted:
            try:
                service.events().delete(
                    calendarId=calendar_id,
                    eventId=ev["id"],
                ).execute()
                deleted += 1
                logger.info("[%s] Deleted: %s (no longer in source)", label, ev.get("summary", ma_id))
            except HttpError as e:
                logger.error("[%s] Delete error for %s: %s", label, ma_id, e)
                errors += 1

    logger.info(
        "[%s] created=%d  updated=%d  deleted=%d  errors=%d",
        label, created, updated, deleted, errors,
    )
    return {"created": created, "updated": updated, "deleted": deleted, "errors": errors}


# -- Entry point ---------------------------------------------------------------
def sync_all() -> int:
    logger.info("MA Hunting Calendar sync started")

    all_rows = load_seasons()

    hunting_rows   = [r for r in all_rows if r["category"] == "hunting"]
    furbearer_rows = [r for r in all_rows if r["category"] == "furbearer"]
    migratory_rows = [r for r in all_rows if r["category"] == "migratory"]

    logger.info(
        "Rows -- hunting: %d  furbearer: %d  migratory: %d",
        len(hunting_rows), len(furbearer_rows), len(migratory_rows),
    )

    service = get_calendar_service()
    h = sync_calendar(service, HUNTING_CALENDAR_ID,   hunting_rows,   "Hunting")
    f = sync_calendar(service, FURBEARER_CALENDAR_ID, furbearer_rows, "Furbearer")
    m = sync_calendar(service, MIGRATORY_CALENDAR_ID, migratory_rows, "Migratory")
    errors = h["errors"] + f["errors"] + m["errors"]

    logger.info("Sync complete -- total errors: %d", errors)

    def _fmt(s: dict) -> str:
        return f"created={s['created']}  updated={s['updated']}  deleted={s['deleted']}  errors={s['errors']}"

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    status = "ERRORS" if errors else "OK"
    send_status_email(
        f"[MA Hunting Calendar] Sync {status} — {now}",
        "\n".join([
            "MA Hunting Calendar Sync",
            now,
            "",
            f"  Hunting:    {_fmt(h)}",
            f"  Furbearer:  {_fmt(f)}",
            f"  Migratory:  {_fmt(m)}",
            "",
            f"Total errors: {errors}",
        ]),
    )

    return errors


if __name__ == "__main__":
    sys.exit(sync_all())
